apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
  - name: nginx-abhishek
    image: nginx
    ports:
    - containerPort: 80
  - name: afakharany-watcher
    image: afakharany/watcher

